# Generated by Django 4.0.5 on 2022-06-05 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_day_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main_app.day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(max_length=100),
        ),
    ]
