# Generated by Django 4.0.5 on 2022-06-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['time']},
        ),
    ]
