# Generated by Django 4.0.5 on 2022-06-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_day_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='memo',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
